on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container: docker.io/library/postgres:15
    steps:
      - run: |
          pg_isready
          echo $?
