on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        image:
          - docker.io/library/postgres:15
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: ${{ matrix.image }}
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - run: |
          psql -l
        env:
          # The hostname used to communicate with the PostgreSQL service container
          PGHOST: postgres
          # The default PostgreSQL port
          PGPORT: 5432
          PGPASSWORD: postgres
