on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        image:
          - docker.io/library/postgres:15
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: ${{ matrix.image }}
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - run: bash -eux step1-fixture.sh
      - run: bash -eux step2-output.sh
      - run: bash  -u  step3-check.sh
    env:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: test
      PGUSER: postgres
      PGPASSWORD: postgres
